// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/money-hub/MoneyDodo.service/deal/pkg/endpoint"
	service "github.com/money-hub/MoneyDodo.service/deal/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"GetDealByDID":       {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetDealByDID", logger))},
		"GetDealByState":     {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetDealByState", logger))},
		"GetUserDealByState": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetUserDealByState", logger))},
		"PostAcceptDeal":     {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PostAcceptDeal", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetUserDealByState"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetUserDealByState")), endpoint.InstrumentingMiddleware(duration.With("method", "GetUserDealByState"))}
	mw["GetDealByDID"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetDealByDID")), endpoint.InstrumentingMiddleware(duration.With("method", "GetDealByDID"))}
	mw["GetDealByState"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetDealByState")), endpoint.InstrumentingMiddleware(duration.With("method", "GetDealByState"))}
	mw["PostAcceptDeal"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PostAcceptDeal")), endpoint.InstrumentingMiddleware(duration.With("method", "PostAcceptDeal"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetUserDealByState", "GetDealByDID", "GetDealByState", "PostAcceptDeal"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
