// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/money-hub/MoneyDodo.service/deal/pkg/endpoint"
	"github.com/money-hub/MoneyDodo.service/middleware"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	m.Use(middleware.GetTokenInfo)
	makeGetUserDealByStateHandler(m, endpoints, options["GetUserDealByState"])
	makeGetDealByDIDHandler(m, endpoints, options["GetDealByDID"])
	makeGetDealByStateHandler(m, endpoints, options["GetDealByState"])
	makePostAcceptDealHandler(m, endpoints, options["PostAcceptDeal"])
	return m
}
