// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/money-hub/MoneyDodo.service/user/pkg/endpoint"
	http1 "github.com/money-hub/MoneyDodo.service/user/pkg/http"
	service "github.com/money-hub/MoneyDodo.service/user/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"Delete":  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Delete", logger))},
		"GetAll":  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAll", logger))},
		"GetSpec": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetSpec", logger))},
		"GetUDF":  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetUDF", logger))},
		"Patch":   {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Patch", logger))},
		"Post":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Post", logger))},
		"Put":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Put", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetSpec"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetSpec")), endpoint.InstrumentingMiddleware(duration.With("method", "GetSpec"))}
	mw["GetAll"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAll")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAll"))}
	mw["GetUDF"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetUDF")), endpoint.InstrumentingMiddleware(duration.With("method", "GetUDF"))}
	mw["Post"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Post")), endpoint.InstrumentingMiddleware(duration.With("method", "Post"))}
	mw["Patch"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Patch")), endpoint.InstrumentingMiddleware(duration.With("method", "Patch"))}
	mw["Put"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Put")), endpoint.InstrumentingMiddleware(duration.With("method", "Put"))}
	mw["Delete"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Delete")), endpoint.InstrumentingMiddleware(duration.With("method", "Delete"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetSpec", "GetAll", "GetUDF", "Post", "Patch", "Put", "Delete"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
