// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/money-hub/MoneyDodo.service/review/pkg/endpoint"
	service "github.com/money-hub/MoneyDodo.service/review/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"GetReview":  {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetReview", logger))},
		"GetReviews": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetReviews", logger))},
		"PostReview": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PostReview", logger))},
		"PutReview":  {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PutReview", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["PostReview"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PostReview")), endpoint.InstrumentingMiddleware(duration.With("method", "PostReview"))}
	mw["GetReview"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetReview")), endpoint.InstrumentingMiddleware(duration.With("method", "GetReview"))}
	mw["GetReviews"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetReviews")), endpoint.InstrumentingMiddleware(duration.With("method", "GetReviews"))}
	mw["PutReview"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PutReview")), endpoint.InstrumentingMiddleware(duration.With("method", "PutReview"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"PostReview", "GetReview", "GetReviews", "PutReview"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
