// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/money-hub/MoneyDodo.service/comment/pkg/endpoint"
	service "github.com/money-hub/MoneyDodo.service/comment/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CancelLikeComment": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CancelLikeComment", logger))},
		"ChangeComment":     {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ChangeComment", logger))},
		"DeleteComment":     {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteComment", logger))},
		"GetComment":        {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetComment", logger))},
		"LikeComment":       {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "LikeComment", logger))},
		"PostComment":       {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PostComment", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetComment")), endpoint.InstrumentingMiddleware(duration.With("method", "GetComment"))}
	mw["PostComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PostComment")), endpoint.InstrumentingMiddleware(duration.With("method", "PostComment"))}
	mw["ChangeComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ChangeComment")), endpoint.InstrumentingMiddleware(duration.With("method", "ChangeComment"))}
	mw["DeleteComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteComment")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteComment"))}
	mw["LikeComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "LikeComment")), endpoint.InstrumentingMiddleware(duration.With("method", "LikeComment"))}
	mw["CancelLikeComment"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CancelLikeComment")), endpoint.InstrumentingMiddleware(duration.With("method", "CancelLikeComment"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetComment", "PostComment", "ChangeComment", "DeleteComment", "LikeComment", "CancelLikeComment"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
