// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/money-hub/MoneyDodo.service/user/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetSpecEndpoint endpoint.Endpoint
	GetAllEndpoint  endpoint.Endpoint
	GetUDFEndpoint  endpoint.Endpoint
	PostEndpoint    endpoint.Endpoint
	PatchEndpoint   endpoint.Endpoint
	PutEndpoint     endpoint.Endpoint
	DeleteEndpoint  endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.UserService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		DeleteEndpoint:  MakeDeleteEndpoint(s),
		GetAllEndpoint:  MakeGetAllEndpoint(s),
		GetSpecEndpoint: MakeGetSpecEndpoint(s),
		GetUDFEndpoint:  MakeGetUDFEndpoint(s),
		PatchEndpoint:   MakePatchEndpoint(s),
		PostEndpoint:    MakePostEndpoint(s),
		PutEndpoint:     MakePutEndpoint(s),
	}
	for _, m := range mdw["GetSpec"] {
		eps.GetSpecEndpoint = m(eps.GetSpecEndpoint)
	}
	for _, m := range mdw["GetAll"] {
		eps.GetAllEndpoint = m(eps.GetAllEndpoint)
	}
	for _, m := range mdw["GetUDF"] {
		eps.GetUDFEndpoint = m(eps.GetUDFEndpoint)
	}
	for _, m := range mdw["Post"] {
		eps.PostEndpoint = m(eps.PostEndpoint)
	}
	for _, m := range mdw["Patch"] {
		eps.PatchEndpoint = m(eps.PatchEndpoint)
	}
	for _, m := range mdw["Put"] {
		eps.PutEndpoint = m(eps.PutEndpoint)
	}
	for _, m := range mdw["Delete"] {
		eps.DeleteEndpoint = m(eps.DeleteEndpoint)
	}
	return eps
}
