// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/money-hub/MoneyDodo.service/certify/pkg/endpoint"
	service "github.com/money-hub/MoneyDodo.service/certify/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"GetAllUnCertify":  {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAllUnCertify", logger))},
		"GetAuthInfo":      {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAuthInfo", logger))},
		"GetUnCertifyInfo": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetUnCertifyInfo", logger))},
		"PostAuthInfo":     {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PostAuthInfo", logger))},
		"PostCertifyState": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PostCertifyState", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetAuthInfo"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAuthInfo")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAuthInfo"))}
	mw["PostAuthInfo"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PostAuthInfo")), endpoint.InstrumentingMiddleware(duration.With("method", "PostAuthInfo"))}
	mw["GetAllUnCertify"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAllUnCertify")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAllUnCertify"))}
	mw["GetUnCertifyInfo"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetUnCertifyInfo")), endpoint.InstrumentingMiddleware(duration.With("method", "GetUnCertifyInfo"))}
	mw["PostCertifyState"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "PostCertifyState")), endpoint.InstrumentingMiddleware(duration.With("method", "PostCertifyState"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetAuthInfo", "PostAuthInfo", "GetAllUnCertify", "GetUnCertifyInfo", "PostCertifyState"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
