// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/money-hub/MoneyDodo.service/comment/pkg/endpoint"
	middleware "github.com/money-hub/MoneyDodo.service/middleware"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	m.Use(middleware.GetTokenInfo)
	makeGetCommentHandler(m, endpoints, options["GetComment"])
	makePostCommentHandler(m, endpoints, options["PostComment"])
	makeChangeCommentHandler(m, endpoints, options["ChangeComment"])
	makeDeleteCommentHandler(m, endpoints, options["DeleteComment"])
	makeLikeCommentHandler(m, endpoints, options["LikeComment"])
	makeCancelLikeCommentHandler(m, endpoints, options["CancelLikeComment"])
	return m
}
